// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Infrastructure_Layer.DbContext_Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20230805100234_001_Data")]
    partial class _001_Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Core_Layer.Domain.Entity_Classes.HumiditySensor", b =>
                {
                    b.Property<Guid>("HumidityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("HumidityValue")
                        .HasColumnType("float");

                    b.HasKey("HumidityId");

                    b.ToTable("Humidities", (string)null);

                    b.HasData(
                        new
                        {
                            HumidityId = new Guid("b7d38156-9955-4a36-ad14-673fb9b14c96"),
                            HumidityValue = 93.25
                        });
                });

            modelBuilder.Entity("WebApi.Core_Layer.Domain.Entity_Classes.TemperatureSensor", b =>
                {
                    b.Property<Guid>("TemperatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TemperatureValue")
                        .HasColumnType("float");

                    b.HasKey("TemperatureId");

                    b.ToTable("Temperatures", (string)null);

                    b.HasData(
                        new
                        {
                            TemperatureId = new Guid("cfa33a92-49d8-44dc-9546-9bf28ef73cdc"),
                            TemperatureValue = 26.550000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
